// ─── Mood ────────────────────────────────────────────────────────────────────

/**
 * Discriminant for the ten fixed moods defined in PRD §3.4.
 * Never widen to `string`; callers should use this union for exhaustive checks.
 */
export type MoodId =
  | 'joy'
  | 'love'
  | 'excited'
  | 'calm'
  | 'grateful'  // legacy — kept so old entries still type-check; not in MOODS array.
  | 'sad'
  | 'angry'
  | 'anxious'
  | 'tired'
  | 'embarrassed'
  // ── New (illustrated set) ──
  | 'sleepy'
  | 'annoyed'
  | 'depressed'
  | 'hurt'
  | 'sick'
  | 'shy'
  | 'surprised'
  | 'listless'
  | 'frustrated'
  | 'proud'
  | 'focused';

/**
 * Discriminant for the 8 fixed daily-activity icons defined in REQ-020.
 * Never widen to `string`.
 */
export type ActivityId =
  | 'meal'
  | 'exercise'
  | 'study'
  | 'cafe'
  | 'walk'
  | 'travel'
  | 'rest'
  | 'work';

/**
 * Union of MoodId and ActivityId. Used wherever either a feeling or an activity
 * can appear (picker, MoodIcon, DiaryEntry.mood).
 * MoodId is a subtype — all existing MoodId values remain valid.
 */
export type PickerId = MoodId | ActivityId;

/**
 * Activity display record (REQ-020).
 * Concrete instances live in src/design-system/activities.ts.
 */
export interface Activity {
  /** Narrowed to the 8-member literal union. */
  id: ActivityId;
  /** Placeholder emoji (e.g. '🍽️'). */
  emoji: string;
  /** Korean label (e.g. '식사'). */
  label: string;
  /** Pastel HEX color (e.g. '#FFD6A5'). */
  color: string;
}

/**
 * Mood display record (PRD §3.3).
 * Concrete instances live in REQ-003 constants; this type is the schema only.
 */
export interface Mood {
  /** Narrowed to the 10-member literal union — not `string`. */
  id: MoodId;
  /** Placeholder emoji (e.g. '😊'). Swappable with custom illustration in a later REQ. */
  emoji: string;
  /** Korean label (e.g. '기쁨'). */
  label: string;
  /** Pastel HEX color for graphs and calendar cells (e.g. '#FFE066'). */
  color: string;
}

// ─── Persona ─────────────────────────────────────────────────────────────────

/**
 * Discriminant for the 14 AI chat personas defined in PRD §3.7.
 */
export type PersonaId =
  | 'friend'
  | 'lover'
  | 'sibling'
  | 'employee'
  | 'boss'
  | 'king'
  | 'grandma'
  | 'therapist'
  | 'daoist'
  | 'shaman'
  | 'junior'
  | 'senior'
  | 'mother'
  | 'father';

/**
 * Persona display and prompt record (PRD §3.7).
 * All fields are required; concrete instances live in REQ-004 constants.
 */
export interface Persona {
  id: PersonaId;
  emoji: string;
  /** Korean UI label (e.g. '친구'). */
  label: string;
  /** One-line Korean description shown in persona-picker UI. */
  shortDesc: string;
  /** Injected into the LLM system prompt (PRD §3.8.1 template). */
  systemPrompt: string;
  /** Shown as the AI's opening message when a session starts. */
  sampleGreeting: string;
}

// ─── Photo ───────────────────────────────────────────────────────────────────

/**
 * Attached photo stored as base64 inside a DiaryEntry (PRD §3.2).
 * Compression and size enforcement are deferred to REQ-011.
 */
export interface Photo {
  /** UUID generated by generateId(). */
  id: string;
  /**
   * Image URL — either a base64 data URL (legacy, Phase ≤2) or a Supabase
   * Storage public URL (Phase 3+). Both render directly in <img src>.
   */
  dataUrl: string;
  /**
   * Path inside the Supabase Storage bucket (`<user_id>/<photo_id>.<ext>`).
   * Present for Phase 3+ photos; undefined for legacy base64 photos so the
   * deleter knows whether a storage cleanup is needed.
   */
  storagePath?: string;
  width: number;
  height: number;
  /** ISO 8601 timestamp of when the photo was attached. */
  addedAt: string;
}

// ─── DiaryEntry ──────────────────────────────────────────────────────────────

/**
 * One diary entry (PRD §3.1).
 * Invariant: at most one DiaryEntry per `date` in the stored collection (PRD §9).
 */
export interface DiaryEntry {
  /** UUID generated by generateId(). */
  id: string;
  /**
   * Calendar date the entry belongs to, format "YYYY-MM-DD".
   * Not the creation timestamp — a user may write yesterday's entry today.
   */
  date: string;
  mood: PickerId;
  /** Plain text body. May contain time markers embedded by the UI. */
  text: string;
  textAlign: 'left' | 'center';
  /** Ordered array of attached photos. Empty array when no photos. */
  photos: Photo[];
  /** ISO 8601 creation timestamp. */
  createdAt: string;
  /** ISO 8601 timestamp of last edit. Equal to createdAt on first save. */
  updatedAt: string;
  /**
   * Origin store for this entry. Set by the reader (useDiaries) — never
   * persisted to either backend. Used by UI badges and by writers that
   * need to delete from the original store.
   */
  _storedIn?: StorageBackend;
}

// ─── ChatMessage ─────────────────────────────────────────────────────────────

/**
 * One message in an AI chat session (PRD §3.6).
 */
export interface ChatMessage {
  /** UUID generated by generateId(). */
  id: string;
  role: 'user' | 'assistant';
  content: string;
  /** ISO 8601 timestamp. */
  timestamp: string;
  /**
   * DiaryEntry ids cited by the assistant in this message.
   * Present only on assistant messages that cite diary entries; absent otherwise.
   */
  citedDiaryIds?: string[];
}

// ─── SearchConversation ──────────────────────────────────────────────────────

/**
 * One AI chat session (PRD §3.5).
 * A closed session (isClosed: true) accepts no further messages.
 * Empty sessions (messages.length === 0) must not be persisted.
 */
export interface SearchConversation {
  /** UUID generated by generateId(). */
  id: string;
  personaId: PersonaId;
  /**
   * Auto-generated from the first user message.
   * Falls back to '새 대화' when no message has been sent yet.
   */
  title: string;
  messages: ChatMessage[];
  /** ISO 8601 timestamp when the session was created. */
  startedAt: string;
  /** ISO 8601 timestamp of the most recent message (used for sort). */
  lastMessageAt: string;
  /**
   * When true, the UI must not show an input box and must not call upsertConversation
   * with new messages. All persisted past conversations are closed.
   */
  isClosed: boolean;
}

// ─── Settings ────────────────────────────────────────────────────────────────

/**
 * User settings singleton (PRD §3.9).
 *
 * Intentionally wide for MVP — future REQs extend this interface via declaration
 * merging in their own files rather than editing types.ts. Example:
 *
 *   // In a future REQ file:
 *   import type { PersonaId } from '@/lib/storage';
 *   declare module '@/lib/storage' {
 *     interface Settings { defaultPersona?: PersonaId; }
 *   }
 */
/** Where new writes go: in-browser localStorage or Supabase ('cloud'). */
export type StorageBackend = 'local' | 'cloud';

export interface Settings {
  /**
   * User's preferred display name (REQ-USER-NAME). Optional.
   * Injected into AI chat system prompt so personas address the user by name.
   * Trimmed at write time; absent/empty → personas use generic Korean address.
   */
  userName?: string;

  /**
   * Destination for new diary writes. Default 'cloud' (Supabase). 'local' keeps
   * the entry in browser localStorage only — useful for offline drafts and for
   * users who want to keep everything on-device. Read paths return entries
   * from both stores.
   */
  storageBackend?: StorageBackend;

  /**
   * Grammatical/social gender the AI uses to pick Korean address forms
   * (오빠/언니, 형/누나 등). 'neutral' means "don't gender". Set during
   * /onboarding and editable from settings.
   */
  gender?: 'male' | 'female' | 'neutral';

  /**
   * Last persona the user picked for a chat session. Set the first time the
   * user picks on /chat/new and updated whenever they swap personas via the
   * in-session bottom sheet. /chat → "새 채팅" reads this to skip the picker
   * after the first session.
   */
  lastPersonaId?: PersonaId;

  /**
   * True once the user finishes /onboarding (호칭 + 성별 입력). Gates the rest
   * of the app on first login.
   */
  onboardingCompleted?: boolean;

  [key: string]: unknown;
}
